// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct Sum_{
    struct Sum__vtable *vptr;
    int isObjOrArray;
    unsigned length;
    void *forwarding; 
    void *v;
};
struct Doit_{
    struct Doit__vtable *vptr;
    int isObjOrArray;
    unsigned length;
    void *forwarding; 
    void *v;
    struct Refercence *    number_;
    int    size_;
};
// vtables structures
struct Sum__vtable
{
   char* Sum__gc_map; 
};



struct Sum__vtable Sum__vtable_; 
struct Doit__vtable
{
   char* Doit__gc_map; 
  int (*doit_)();
};



struct Doit__vtable Doit__vtable_; 

// methods
void *prev;
int Doit__doit__arguments_gc_map = 1;
int Doit__doit__locals_gc_map = 0;
struct Doit__doit__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Doit__doit_(struct Doit_ * this, int n_)
{
    struct Doit__doit__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Doit__doit__arguments_gc_map;
    frame.locals_gc_map = Doit__doit__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    this->number_ = Tiger_new_array(10);
    *(((int*)(this->number_))+5+1) = 1;
    prev=frame.prev;
    return *(((int*)(this->number_))+5+1);
}

// vtables
struct Sum__vtable Sum__vtable_ = 
{
"",
};

struct Doit__vtable Doit__vtable_ = 
{
"10",
  Doit__doit_,
};


// main method
int Tiger_main_arguments_gc_map = 0;
int Tiger_main_locals_gc_map = 0;
struct Tiger_main_gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    struct Doit_ * x_0;
};
int Tiger_main ()
{
    struct Tiger_main_gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tiger_main_arguments_gc_map;
    frame.locals_gc_map  = Tiger_main_locals_gc_map;
     frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    struct Doit_ * x_0;
    System_out_println ((x_0=((struct Doit_*)(Tiger_new (&Doit__vtable_, sizeof(struct Doit_)))), x_0->vptr->doit_(x_0, 101)));
}




