// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct TreeVisitor_{
    struct TreeVisitor__vtable *vptr;
    int isObjOrArray;
    unsigned length;
    void *forwarding; 
    void *v;
};
struct TV_{
    struct TV__vtable *vptr;
    int isObjOrArray;
    unsigned length;
    void *forwarding; 
    void *v;
};
struct Tree_{
    struct Tree__vtable *vptr;
    int isObjOrArray;
    unsigned length;
    void *forwarding; 
    void *v;
    struct Tree_ *    left_;
    struct Tree_ *    right_;
    int    key_;
    int    has_left_;
    int    has_right_;
    struct Tree_ *    my_null_;
};
struct Visitor_{
    struct Visitor__vtable *vptr;
    int isObjOrArray;
    unsigned length;
    void *forwarding; 
    void *v;
    struct Tree_ *    l_;
    struct Tree_ *    r_;
};
struct MyVisitor_{
    struct MyVisitor__vtable *vptr;
    int isObjOrArray;
    unsigned length;
    void *forwarding; 
    void *v;
    struct Tree_ *    l_;
    struct Tree_ *    r_;
};
// vtables structures
struct TreeVisitor__vtable
{
   char* TreeVisitor__gc_map; 
};



struct TreeVisitor__vtable TreeVisitor__vtable_; 
struct TV__vtable
{
   char* TV__gc_map; 
  int (*Start_)();
};



struct TV__vtable TV__vtable_; 
struct Tree__vtable
{
   char* Tree__gc_map; 
  int (*Init_)();
  int (*SetRight_)();
  int (*SetLeft_)();
  struct Tree_ * (*GetRight_)();
  struct Tree_ * (*GetLeft_)();
  int (*GetKey_)();
  int (*SetKey_)();
  int (*GetHas_Right_)();
  int (*GetHas_Left_)();
  int (*SetHas_Left_)();
  int (*SetHas_Right_)();
  int (*Compare_)();
  int (*Insert_)();
  int (*Delete_)();
  int (*Remove_)();
  int (*RemoveRight_)();
  int (*RemoveLeft_)();
  int (*Search_)();
  int (*Print_)();
  int (*RecPrint_)();
  int (*accept_)();
};



struct Tree__vtable Tree__vtable_; 
struct Visitor__vtable
{
   char* Visitor__gc_map; 
  int (*visit_)();
};



struct Visitor__vtable Visitor__vtable_; 
struct MyVisitor__vtable
{
   char* MyVisitor__gc_map; 
  int (*visit_)();
};



struct MyVisitor__vtable MyVisitor__vtable_; 

// methods
void *prev;
int TV__Start__arguments_gc_map = 1;
int TV__Start__locals_gc_map = 0;
struct TV__Start__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int TV__Start_(struct TV_ * this)
{
    struct Tree_ * root_;
    int ntb_;
    int nti_;
    struct MyVisitor_ * v_;
    struct Tree_ * x_1;
    struct Tree_ * x_2;
    struct Tree_ * x_3;
    struct Tree_ * x_4;
    struct Tree_ * x_5;
    struct Tree_ * x_6;
    struct Tree_ * x_7;
    struct Tree_ * x_8;
    struct Tree_ * x_9;
    struct Tree_ * x_10;
    struct Tree_ * x_11;
    struct Tree_ * x_12;
    struct Tree_ * x_13;
    struct Tree_ * x_14;
    struct Tree_ * x_15;
    struct Tree_ * x_16;
    struct Tree_ * x_17;
    struct Tree_ * x_18;
    struct Tree_ * x_19;
    struct TV__Start__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = TV__Start__arguments_gc_map;
    frame.locals_gc_map = TV__Start__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    root_ = ((struct Tree_*)(Tiger_new (&Tree__vtable_, sizeof(struct Tree_))));
    ntb_ = (x_1=root_, x_1->vptr->Init_(x_1, 16));
    ntb_ = (x_2=root_, x_2->vptr->Print_(x_2));
        System_out_println (100000000);
    ntb_ = (x_3=root_, x_3->vptr->Insert_(x_3, 8));
    ntb_ = (x_4=root_, x_4->vptr->Insert_(x_4, 24));
    ntb_ = (x_5=root_, x_5->vptr->Insert_(x_5, 4));
    ntb_ = (x_6=root_, x_6->vptr->Insert_(x_6, 12));
    ntb_ = (x_7=root_, x_7->vptr->Insert_(x_7, 20));
    ntb_ = (x_8=root_, x_8->vptr->Insert_(x_8, 28));
    ntb_ = (x_9=root_, x_9->vptr->Insert_(x_9, 14));
    ntb_ = (x_10=root_, x_10->vptr->Print_(x_10));
        System_out_println (100000000);
    v_ = ((struct MyVisitor_*)(Tiger_new (&MyVisitor__vtable_, sizeof(struct MyVisitor_))));
        System_out_println (50000000);
    nti_ = (x_11=root_, x_11->vptr->accept_(x_11, v_));
        System_out_println (100000000);
        System_out_println ((x_12=root_, x_12->vptr->Search_(x_12, 24)));
        System_out_println ((x_13=root_, x_13->vptr->Search_(x_13, 12)));
        System_out_println ((x_14=root_, x_14->vptr->Search_(x_14, 16)));
        System_out_println ((x_15=root_, x_15->vptr->Search_(x_15, 50)));
        System_out_println ((x_16=root_, x_16->vptr->Search_(x_16, 12)));
    ntb_ = (x_17=root_, x_17->vptr->Delete_(x_17, 12));
    ntb_ = (x_18=root_, x_18->vptr->Print_(x_18));
        System_out_println ((x_19=root_, x_19->vptr->Search_(x_19, 12)));
    prev=frame.prev;
    return 0;
}
int Tree__Init__arguments_gc_map = 1;
int Tree__Init__locals_gc_map = 0;
struct Tree__Init__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Tree__Init_(struct Tree_ * this, int v_key_)
{
    struct Tree__Init__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__Init__arguments_gc_map;
    frame.locals_gc_map = Tree__Init__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    this->key_ = v_key_;
    this->has_left_ = 0;
    this->has_right_ = 0;
    prev=frame.prev;
    return 1;
}
int Tree__SetRight__arguments_gc_map = 2;
int Tree__SetRight__locals_gc_map = 0;
struct Tree__SetRight__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
    void *y_1;
};
int Tree__SetRight_(struct Tree_ * this, struct Tree_ * rn_)
{
    struct Tree__SetRight__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__SetRight__arguments_gc_map;
    frame.locals_gc_map = Tree__SetRight__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    frame.y_1 = &rn_;
    this->right_ = rn_;
    prev=frame.prev;
    return 1;
}
int Tree__SetLeft__arguments_gc_map = 2;
int Tree__SetLeft__locals_gc_map = 0;
struct Tree__SetLeft__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
    void *y_1;
};
int Tree__SetLeft_(struct Tree_ * this, struct Tree_ * ln_)
{
    struct Tree__SetLeft__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__SetLeft__arguments_gc_map;
    frame.locals_gc_map = Tree__SetLeft__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    frame.y_1 = &ln_;
    this->left_ = ln_;
    prev=frame.prev;
    return 1;
}
int Tree__GetRight__arguments_gc_map = 1;
int Tree__GetRight__locals_gc_map = 0;
struct Tree__GetRight__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
struct Tree_ * Tree__GetRight_(struct Tree_ * this)
{
    struct Tree__GetRight__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__GetRight__arguments_gc_map;
    frame.locals_gc_map = Tree__GetRight__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    prev=frame.prev;
    return this->right_;
}
int Tree__GetLeft__arguments_gc_map = 1;
int Tree__GetLeft__locals_gc_map = 0;
struct Tree__GetLeft__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
struct Tree_ * Tree__GetLeft_(struct Tree_ * this)
{
    struct Tree__GetLeft__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__GetLeft__arguments_gc_map;
    frame.locals_gc_map = Tree__GetLeft__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    prev=frame.prev;
    return this->left_;
}
int Tree__GetKey__arguments_gc_map = 1;
int Tree__GetKey__locals_gc_map = 0;
struct Tree__GetKey__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Tree__GetKey_(struct Tree_ * this)
{
    struct Tree__GetKey__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__GetKey__arguments_gc_map;
    frame.locals_gc_map = Tree__GetKey__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    prev=frame.prev;
    return this->key_;
}
int Tree__SetKey__arguments_gc_map = 1;
int Tree__SetKey__locals_gc_map = 0;
struct Tree__SetKey__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Tree__SetKey_(struct Tree_ * this, int v_key_)
{
    struct Tree__SetKey__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__SetKey__arguments_gc_map;
    frame.locals_gc_map = Tree__SetKey__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    this->key_ = v_key_;
    prev=frame.prev;
    return 1;
}
int Tree__GetHas_Right__arguments_gc_map = 1;
int Tree__GetHas_Right__locals_gc_map = 0;
struct Tree__GetHas_Right__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Tree__GetHas_Right_(struct Tree_ * this)
{
    struct Tree__GetHas_Right__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__GetHas_Right__arguments_gc_map;
    frame.locals_gc_map = Tree__GetHas_Right__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    prev=frame.prev;
    return this->has_right_;
}
int Tree__GetHas_Left__arguments_gc_map = 1;
int Tree__GetHas_Left__locals_gc_map = 0;
struct Tree__GetHas_Left__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Tree__GetHas_Left_(struct Tree_ * this)
{
    struct Tree__GetHas_Left__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__GetHas_Left__arguments_gc_map;
    frame.locals_gc_map = Tree__GetHas_Left__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    prev=frame.prev;
    return this->has_left_;
}
int Tree__SetHas_Left__arguments_gc_map = 1;
int Tree__SetHas_Left__locals_gc_map = 0;
struct Tree__SetHas_Left__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Tree__SetHas_Left_(struct Tree_ * this, int val_)
{
    struct Tree__SetHas_Left__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__SetHas_Left__arguments_gc_map;
    frame.locals_gc_map = Tree__SetHas_Left__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    this->has_left_ = val_;
    prev=frame.prev;
    return 1;
}
int Tree__SetHas_Right__arguments_gc_map = 1;
int Tree__SetHas_Right__locals_gc_map = 0;
struct Tree__SetHas_Right__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Tree__SetHas_Right_(struct Tree_ * this, int val_)
{
    struct Tree__SetHas_Right__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__SetHas_Right__arguments_gc_map;
    frame.locals_gc_map = Tree__SetHas_Right__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    this->has_right_ = val_;
    prev=frame.prev;
    return 1;
}
int Tree__Compare__arguments_gc_map = 1;
int Tree__Compare__locals_gc_map = 0;
struct Tree__Compare__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Tree__Compare_(struct Tree_ * this, int num1_, int num2_)
{
    int ntb_;
    int nti_;
    struct Tree__Compare__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__Compare__arguments_gc_map;
    frame.locals_gc_map = Tree__Compare__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    ntb_ = 0;
    nti_ = num2_ + 1;
    if (num1_ < num2_){
        ntb_ = 0;
    }else{
        if (!(num1_ < nti_)){
            ntb_ = 0;
        }else{
            ntb_ = 1;
        }
    }
    prev=frame.prev;
    return ntb_;
}
int Tree__Insert__arguments_gc_map = 1;
int Tree__Insert__locals_gc_map = 0;
struct Tree__Insert__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Tree__Insert_(struct Tree_ * this, int v_key_)
{
    struct Tree_ * new_node_;
    int ntb_;
    struct Tree_ * current_node_;
    int cont_;
    int key_aux_;
    struct Tree_ * x_20;
    struct Tree_ * x_21;
    struct Tree_ * x_22;
    struct Tree_ * x_23;
    struct Tree_ * x_24;
    struct Tree_ * x_25;
    struct Tree_ * x_26;
    struct Tree_ * x_27;
    struct Tree_ * x_28;
    struct Tree_ * x_29;
    struct Tree__Insert__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__Insert__arguments_gc_map;
    frame.locals_gc_map = Tree__Insert__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    new_node_ = ((struct Tree_*)(Tiger_new (&Tree__vtable_, sizeof(struct Tree_))));
    ntb_ = (x_20=new_node_, x_20->vptr->Init_(x_20, v_key_));
    current_node_ = this;
    cont_ = 1;
    while (cont_){
        key_aux_ = (x_21=current_node_, x_21->vptr->GetKey_(x_21));
        if (v_key_ < key_aux_){
            if ((x_22=current_node_, x_22->vptr->GetHas_Left_(x_22))){
                current_node_ = (x_23=current_node_, x_23->vptr->GetLeft_(x_23));
            }else{
                cont_ = 0;
                ntb_ = (x_24=current_node_, x_24->vptr->SetHas_Left_(x_24, 1));
                ntb_ = (x_25=current_node_, x_25->vptr->SetLeft_(x_25, new_node_));
            }
        }else{
            if ((x_26=current_node_, x_26->vptr->GetHas_Right_(x_26))){
                current_node_ = (x_27=current_node_, x_27->vptr->GetRight_(x_27));
            }else{
                cont_ = 0;
                ntb_ = (x_28=current_node_, x_28->vptr->SetHas_Right_(x_28, 1));
                ntb_ = (x_29=current_node_, x_29->vptr->SetRight_(x_29, new_node_));
            }
        }
    }
    prev=frame.prev;
    return 1;
}
int Tree__Delete__arguments_gc_map = 1;
int Tree__Delete__locals_gc_map = 0;
struct Tree__Delete__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Tree__Delete_(struct Tree_ * this, int v_key_)
{
    struct Tree_ * current_node_;
    struct Tree_ * parent_node_;
    int cont_;
    int found_;
    int ntb_;
    int is_root_;
    int key_aux_;
    struct Tree_ * x_30;
    struct Tree_ * x_31;
    struct Tree_ * x_32;
    struct Tree_ * x_33;
    struct Tree_ * x_34;
    struct Tree_ * x_35;
    struct Tree_ * x_36;
    struct Tree_ * x_37;
    struct Tree_ * x_38;
    struct Tree__Delete__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__Delete__arguments_gc_map;
    frame.locals_gc_map = Tree__Delete__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    current_node_ = this;
    parent_node_ = this;
    cont_ = 1;
    found_ = 0;
    is_root_ = 1;
    while (cont_){
        key_aux_ = (x_30=current_node_, x_30->vptr->GetKey_(x_30));
        if (v_key_ < key_aux_){
            if ((x_31=current_node_, x_31->vptr->GetHas_Left_(x_31))){
                parent_node_ = current_node_;
                current_node_ = (x_32=current_node_, x_32->vptr->GetLeft_(x_32));
            }else{
                cont_ = 0;
            }
        }else{
            if (key_aux_ < v_key_){
                if ((x_33=current_node_, x_33->vptr->GetHas_Right_(x_33))){
                    parent_node_ = current_node_;
                    current_node_ = (x_34=current_node_, x_34->vptr->GetRight_(x_34));
                }else{
                    cont_ = 0;
                }
            }else{
                if (is_root_){
                    if (!(x_35=current_node_, x_35->vptr->GetHas_Right_(x_35)) && !(x_36=current_node_, x_36->vptr->GetHas_Left_(x_36))){
                        ntb_ = 1;
                    }else{
                        ntb_ = (x_37=this, x_37->vptr->Remove_(x_37, parent_node_, current_node_));
                    }
                }else{
                    ntb_ = (x_38=this, x_38->vptr->Remove_(x_38, parent_node_, current_node_));
                }
                found_ = 1;
                cont_ = 0;
            }
        }
        is_root_ = 0;
    }
    prev=frame.prev;
    return found_;
}
int Tree__Remove__arguments_gc_map = 3;
int Tree__Remove__locals_gc_map = 0;
struct Tree__Remove__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
    void *y_1;
    void *y_2;
};
int Tree__Remove_(struct Tree_ * this, struct Tree_ * p_node_, struct Tree_ * c_node_)
{
    int ntb_;
    int auxkey1_;
    int auxkey2_;
    struct Tree_ * x_39;
    struct Tree_ * x_40;
    struct Tree_ * x_41;
    struct Tree_ * x_42;
    struct Tree_ * x_43;
    struct Tree_ * x_44;
    struct Tree_ * x_45;
    struct Tree_ * x_46;
    struct Tree_ * x_47;
    struct Tree_ * x_48;
    struct Tree_ * x_49;
    struct Tree_ * x_50;
    struct Tree__Remove__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__Remove__arguments_gc_map;
    frame.locals_gc_map = Tree__Remove__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    frame.y_1 = &p_node_;
    frame.y_2 = &c_node_;
    if ((x_39=c_node_, x_39->vptr->GetHas_Left_(x_39))){
        ntb_ = (x_40=this, x_40->vptr->RemoveLeft_(x_40, p_node_, c_node_));
    }else{
        if ((x_41=c_node_, x_41->vptr->GetHas_Right_(x_41))){
            ntb_ = (x_42=this, x_42->vptr->RemoveRight_(x_42, p_node_, c_node_));
        }else{
            auxkey1_ = (x_43=c_node_, x_43->vptr->GetKey_(x_43));
            auxkey2_ = (x_45=((x_44=p_node_, x_44->vptr->GetLeft_(x_44))), x_45->vptr->GetKey_(x_45));
            if ((x_46=this, x_46->vptr->Compare_(x_46, auxkey1_, auxkey2_))){
                ntb_ = (x_47=p_node_, x_47->vptr->SetLeft_(x_47, this->my_null_));
                ntb_ = (x_48=p_node_, x_48->vptr->SetHas_Left_(x_48, 0));
            }else{
                ntb_ = (x_49=p_node_, x_49->vptr->SetRight_(x_49, this->my_null_));
                ntb_ = (x_50=p_node_, x_50->vptr->SetHas_Right_(x_50, 0));
            }
        }
    }
    prev=frame.prev;
    return 1;
}
int Tree__RemoveRight__arguments_gc_map = 3;
int Tree__RemoveRight__locals_gc_map = 0;
struct Tree__RemoveRight__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
    void *y_1;
    void *y_2;
};
int Tree__RemoveRight_(struct Tree_ * this, struct Tree_ * p_node_, struct Tree_ * c_node_)
{
    int ntb_;
    struct Tree_ * x_51;
    struct Tree_ * x_52;
    struct Tree_ * x_53;
    struct Tree_ * x_54;
    struct Tree_ * x_55;
    struct Tree_ * x_56;
    struct Tree_ * x_57;
    struct Tree__RemoveRight__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__RemoveRight__arguments_gc_map;
    frame.locals_gc_map = Tree__RemoveRight__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    frame.y_1 = &p_node_;
    frame.y_2 = &c_node_;
    while ((x_51=c_node_, x_51->vptr->GetHas_Right_(x_51))){
        ntb_ = (x_52=c_node_, x_52->vptr->SetKey_(x_52, (x_54=((x_53=c_node_, x_53->vptr->GetRight_(x_53))), x_54->vptr->GetKey_(x_54))));
        p_node_ = c_node_;
        c_node_ = (x_55=c_node_, x_55->vptr->GetRight_(x_55));
    }
    ntb_ = (x_56=p_node_, x_56->vptr->SetRight_(x_56, this->my_null_));
    ntb_ = (x_57=p_node_, x_57->vptr->SetHas_Right_(x_57, 0));
    prev=frame.prev;
    return 1;
}
int Tree__RemoveLeft__arguments_gc_map = 3;
int Tree__RemoveLeft__locals_gc_map = 0;
struct Tree__RemoveLeft__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
    void *y_1;
    void *y_2;
};
int Tree__RemoveLeft_(struct Tree_ * this, struct Tree_ * p_node_, struct Tree_ * c_node_)
{
    int ntb_;
    struct Tree_ * x_58;
    struct Tree_ * x_59;
    struct Tree_ * x_60;
    struct Tree_ * x_61;
    struct Tree_ * x_62;
    struct Tree_ * x_63;
    struct Tree_ * x_64;
    struct Tree__RemoveLeft__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__RemoveLeft__arguments_gc_map;
    frame.locals_gc_map = Tree__RemoveLeft__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    frame.y_1 = &p_node_;
    frame.y_2 = &c_node_;
    while ((x_58=c_node_, x_58->vptr->GetHas_Left_(x_58))){
        ntb_ = (x_59=c_node_, x_59->vptr->SetKey_(x_59, (x_61=((x_60=c_node_, x_60->vptr->GetLeft_(x_60))), x_61->vptr->GetKey_(x_61))));
        p_node_ = c_node_;
        c_node_ = (x_62=c_node_, x_62->vptr->GetLeft_(x_62));
    }
    ntb_ = (x_63=p_node_, x_63->vptr->SetLeft_(x_63, this->my_null_));
    ntb_ = (x_64=p_node_, x_64->vptr->SetHas_Left_(x_64, 0));
    prev=frame.prev;
    return 1;
}
int Tree__Search__arguments_gc_map = 1;
int Tree__Search__locals_gc_map = 0;
struct Tree__Search__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Tree__Search_(struct Tree_ * this, int v_key_)
{
    struct Tree_ * current_node_;
    int ifound_;
    int cont_;
    int key_aux_;
    struct Tree_ * x_65;
    struct Tree_ * x_66;
    struct Tree_ * x_67;
    struct Tree_ * x_68;
    struct Tree_ * x_69;
    struct Tree__Search__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__Search__arguments_gc_map;
    frame.locals_gc_map = Tree__Search__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    current_node_ = this;
    cont_ = 1;
    ifound_ = 0;
    while (cont_){
        key_aux_ = (x_65=current_node_, x_65->vptr->GetKey_(x_65));
        if (v_key_ < key_aux_){
            if ((x_66=current_node_, x_66->vptr->GetHas_Left_(x_66))){
                current_node_ = (x_67=current_node_, x_67->vptr->GetLeft_(x_67));
            }else{
                cont_ = 0;
            }
        }else{
            if (key_aux_ < v_key_){
                if ((x_68=current_node_, x_68->vptr->GetHas_Right_(x_68))){
                    current_node_ = (x_69=current_node_, x_69->vptr->GetRight_(x_69));
                }else{
                    cont_ = 0;
                }
            }else{
                ifound_ = 1;
                cont_ = 0;
            }
        }
    }
    prev=frame.prev;
    return ifound_;
}
int Tree__Print__arguments_gc_map = 1;
int Tree__Print__locals_gc_map = 0;
struct Tree__Print__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
};
int Tree__Print_(struct Tree_ * this)
{
    int ntb_;
    struct Tree_ * current_node_;
    struct Tree_ * x_70;
    struct Tree__Print__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__Print__arguments_gc_map;
    frame.locals_gc_map = Tree__Print__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    current_node_ = this;
    ntb_ = (x_70=this, x_70->vptr->RecPrint_(x_70, current_node_));
    prev=frame.prev;
    return 1;
}
int Tree__RecPrint__arguments_gc_map = 2;
int Tree__RecPrint__locals_gc_map = 0;
struct Tree__RecPrint__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
    void *y_1;
};
int Tree__RecPrint_(struct Tree_ * this, struct Tree_ * node_)
{
    int ntb_;
    struct Tree_ * x_71;
    struct Tree_ * x_72;
    struct Tree_ * x_73;
    struct Tree_ * x_74;
    struct Tree_ * x_75;
    struct Tree_ * x_76;
    struct Tree_ * x_77;
    struct Tree__RecPrint__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__RecPrint__arguments_gc_map;
    frame.locals_gc_map = Tree__RecPrint__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    frame.y_1 = &node_;
    if ((x_71=node_, x_71->vptr->GetHas_Left_(x_71))){
        ntb_ = (x_72=this, x_72->vptr->RecPrint_(x_72, (x_73=node_, x_73->vptr->GetLeft_(x_73))));
    }else{
        ntb_ = 1;
    }
        System_out_println ((x_74=node_, x_74->vptr->GetKey_(x_74)));
    if ((x_75=node_, x_75->vptr->GetHas_Right_(x_75))){
        ntb_ = (x_76=this, x_76->vptr->RecPrint_(x_76, (x_77=node_, x_77->vptr->GetRight_(x_77))));
    }else{
        ntb_ = 1;
    }
    prev=frame.prev;
    return 1;
}
int Tree__accept__arguments_gc_map = 2;
int Tree__accept__locals_gc_map = 0;
struct Tree__accept__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
    void *y_1;
};
int Tree__accept_(struct Tree_ * this, struct Visitor_ * v_)
{
    int nti_;
    struct Visitor_ * x_78;
    struct Tree__accept__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tree__accept__arguments_gc_map;
    frame.locals_gc_map = Tree__accept__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    frame.y_1 = &v_;
        System_out_println (333);
    nti_ = (x_78=v_, x_78->vptr->visit_(x_78, this));
    prev=frame.prev;
    return 0;
}
int Visitor__visit__arguments_gc_map = 2;
int Visitor__visit__locals_gc_map = 0;
struct Visitor__visit__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
    void *y_1;
};
int Visitor__visit_(struct Visitor_ * this, struct Tree_ * n_)
{
    int nti_;
    struct Tree_ * x_79;
    struct Tree_ * x_80;
    struct Tree_ * x_81;
    struct Tree_ * x_82;
    struct Tree_ * x_83;
    struct Tree_ * x_84;
    struct Visitor__visit__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Visitor__visit__arguments_gc_map;
    frame.locals_gc_map = Visitor__visit__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    frame.y_1 = &n_;
    if ((x_79=n_, x_79->vptr->GetHas_Right_(x_79))){
        this->r_ = (x_80=n_, x_80->vptr->GetRight_(x_80));
        nti_ = (x_81=this->r_, x_81->vptr->accept_(x_81, this));
    }else{
        nti_ = 0;
    }
    if ((x_82=n_, x_82->vptr->GetHas_Left_(x_82))){
        this->l_ = (x_83=n_, x_83->vptr->GetLeft_(x_83));
        nti_ = (x_84=this->l_, x_84->vptr->accept_(x_84, this));
    }else{
        nti_ = 0;
    }
    prev=frame.prev;
    return 0;
}
int MyVisitor__visit__arguments_gc_map = 2;
int MyVisitor__visit__locals_gc_map = 0;
struct MyVisitor__visit__gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    void *y_0;
    void *y_1;
};
int MyVisitor__visit_(struct MyVisitor_ * this, struct Tree_ * n_)
{
    int nti_;
    struct Tree_ * x_85;
    struct Tree_ * x_86;
    struct Tree_ * x_87;
    struct Tree_ * x_88;
    struct Tree_ * x_89;
    struct Tree_ * x_90;
    struct Tree_ * x_91;
    struct MyVisitor__visit__gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = MyVisitor__visit__arguments_gc_map;
    frame.locals_gc_map = MyVisitor__visit__locals_gc_map;
    frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    frame.y_0 = &this;
    frame.y_1 = &n_;
    if ((x_85=n_, x_85->vptr->GetHas_Right_(x_85))){
        this->r_ = (x_86=n_, x_86->vptr->GetRight_(x_86));
        nti_ = (x_87=this->r_, x_87->vptr->accept_(x_87, this));
    }else{
        nti_ = 0;
    }
        System_out_println ((x_88=n_, x_88->vptr->GetKey_(x_88)));
    if ((x_89=n_, x_89->vptr->GetHas_Left_(x_89))){
        this->l_ = (x_90=n_, x_90->vptr->GetLeft_(x_90));
        nti_ = (x_91=this->l_, x_91->vptr->accept_(x_91, this));
    }else{
        nti_ = 0;
    }
    prev=frame.prev;
    return 0;
}

// vtables
struct TreeVisitor__vtable TreeVisitor__vtable_ = 
{
"",
};

struct TV__vtable TV__vtable_ = 
{
"",
  TV__Start_,
};

struct Tree__vtable Tree__vtable_ = 
{
"110001",
  Tree__Init_,
  Tree__SetRight_,
  Tree__SetLeft_,
  Tree__GetRight_,
  Tree__GetLeft_,
  Tree__GetKey_,
  Tree__SetKey_,
  Tree__GetHas_Right_,
  Tree__GetHas_Left_,
  Tree__SetHas_Left_,
  Tree__SetHas_Right_,
  Tree__Compare_,
  Tree__Insert_,
  Tree__Delete_,
  Tree__Remove_,
  Tree__RemoveRight_,
  Tree__RemoveLeft_,
  Tree__Search_,
  Tree__Print_,
  Tree__RecPrint_,
  Tree__accept_,
};

struct Visitor__vtable Visitor__vtable_ = 
{
"11",
  Visitor__visit_,
};

struct MyVisitor__vtable MyVisitor__vtable_ = 
{
"11",
  MyVisitor__visit_,
};


// main method
int Tiger_main_arguments_gc_map = 0;
int Tiger_main_locals_gc_map = 0;
struct Tiger_main_gc_frame{
      void *prev;
      int arguments_gc_map;
      int locals_gc_map;
      void *arguments_base_address;
      void *v;
    struct TV_ * x_0;
};
int Tiger_main ()
{
    struct Tiger_main_gc_frame frame;
    frame.prev = prev;
    prev = &frame;
    frame.arguments_gc_map = Tiger_main_arguments_gc_map;
    frame.locals_gc_map  = Tiger_main_locals_gc_map;
     frame.arguments_base_address = &(frame.v) + frame.locals_gc_map + 1;
    frame.v = &(frame.v) + 1;
    struct TV_ * x_0;
    System_out_println ((x_0=((struct TV_*)(Tiger_new (&TV__vtable_, sizeof(struct TV_)))), x_0->vptr->Start_(x_0)));
}




